project:
  type: website

website:
  title: "R for Biochemists"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rforbiochemists
format:
  html:
    theme: flatly
    css: styles.css

execute:
  freeze: auto



